export const facts = [
  "💫 I have a very fast and calculating mind",
  "⚡ My favorite programming language is JavaScript",
  "🎨 I paid for a course on three.js but never finished it",
  "🚀 I prefer vanilla css over frameworks",
  "✨ My best Javascript framework is Vue.js",
  "💻 I believe in writing clean, maintainable code with TypeScript",
  "🎮 I can spend hours optimizing performance and user experience",
  "🌟 I'm always learning new web technologies and frameworks",
  "🔥 I love the challenge of solving complex coding problems",
  "🎯 I'm a perfectionist when it comes to UI/UX details",
  "🌐 I love crocheting",
  "I have little to no problem learning new things and I am very curious",
  "I studied Civil and Environmental Engineering in the University of Port Harcourt",
  "I am a first class graduate",
  "I was the best Graduating Student in my secondary and university, proof that I am always the best",
  "I am lazy and hardworking at the same time",
  "I want to be rich rich",
];
export const SKILLS = [
  {
    id: "javascript",
    label: "JavaScript",
    color1: "#ffd86b",
    color2: "#ff9f47",
    text: "Core language for web & app development.",
  },
  {
    id: "typescript",
    label: "TypeScript",
    color1: "#85d1ff",
    color2: "#6fa7ff",
    text: "Typed JS for large, scalable projects.",
  },
  {
    id: "react-native",
    label: "React Native",
    color1: "#8ee6ff",
    color2: "#508bff",
    text: "Cross-platform mobile apps.",
  },
  {
    id: "capacitor",
    label: "Capacitor",
    color1: "#b78bff",
    color2: "#ff6bb0",
    text: "Native runtime for web-based mobile apps.",
  },
  {
    id: "nuxt",
    label: "Nuxt",
    color1: "#7ee0ff",
    color2: "#7b6bff",
    text: "SSR & full-stack Vue framework.",
  },
  {
    id: "supabase",
    label: "Supabase",
    color1: "#7fffd4",
    color2: "#28cba5",
    text: "Auth, DB, APIs & storage backend.",
  },
  {
    id: "node-red",
    label: "Node-RED",
    color1: "#ff6161",
    color2: "#ff3434",
    text: "Automation & low-code flows.",
  },
  {
    id: "vuetify",
    label: "Vuetify",
    color1: "#caa6ff",
    color2: "#8e6bff",
    text: "Material UI Framework.",
  },
  {
    id: "python",
    label: "Python",
    color1: "#f7db6a",
    color2: "#4b8bff",
    text: "Scripting, automation & backend tooling.",
  },
  {
    id: "aws-lambda",
    label: "AWS (Lambda)",
    color1: "#ffa34b",
    color2: "#ff7f00",
    text: "Serverless compute & cloud services.",
  },
  {
    id: "bootstrap",
    label: "Bootstrap",
    color1: "#ba8bff",
    color2: "#7952b3",
    text: "CSS Framework for layouts & UIs.",
  },
  {
    id: "vue.js",
    label: "Vue.js",
    color1: "#67f2a9",
    color2: "#32c2a0",
    text: "Reactive UI framework.",
  },
];
export const crochetImages = [
  "/hobby/27A63DF5-857C-483D-8208-A3F60063C3BE.JPG",
  "/hobby/ED115DE1-DAD1-48F8-9576-E6B872DB3B89.JPG",
  "/hobby/IMG_1506.JPG",
  "/hobby/IMG_9165.JPG",
  "/hobby/IMG_9166.JPG",
  "/hobby/IMG_9177.JPG",
  "/hobby/IMG_9178.JPG",
  "/hobby/IMG_9180.JPG",
  "/hobby/IMG_9183.JPG",
  "/hobby/IMG_9189.JPG",
  "/hobby/IMG_9192.JPG",
  "/hobby/IMG_9202.JPG",
  "/hobby/IMG_9207.JPG",
  "/hobby/IMG_9217.JPG",
  "/hobby/IMG_9218.JPG",
  "/hobby/IMG_9220.JPG",
  "/hobby/IMG_9387.JPG",
  "/hobby/IMG_9391.JPG",
  "/hobby/IMG_9398.JPG",
  "/hobby/IMG_9402.JPG",
  "/hobby/IMG_9404.JPG",
  "/hobby/IMG_9408.JPG",
  "/hobby/IMG_9409.JPG",
  "/hobby/IMG_9420.JPG",
  "/hobby/IMG_9808.JPG",
];
export const planetPositions = [
  { top: "20%", left: "20%" },
  { top: "30%", left: "70%" },
  { top: "60%", left: "25%" },
  { top: "70%", left: "75%" },
  { top: "45%", left: "45%" },
];
